### ISSUE TITLE
stringent protein similarity results in less clusters

### ISSUE THREAD

**Issue by ZhangDengwei** [medema-group/BiG-MAP#13]
Hi,

I would like to set a stringent protein similarity to deduplicate my BGCs. I set the parameter `-tg` from 0.5 to 0.9, which should be expected to generate less similar clusters and more representative cluster sequences. However, the result is the opposite. I check the code of script `BiG-MAP.family.py` and found the overlap was defined as `overlap = 1-(float(no1)/float(no2))`, making me quite confused. The last column from `MASH` distance file refers to "Matching-hashes", I think "(float(no1)/float(no2)" should be the similarity between two clusters? Or do I misunderstand anything?

```
$ grep -c ">" 0.5/BiG-MAP.GCF.fna
40
$ grep -c ">" 0.9/BiG-MAP.GCF.fna
32
```

**Comment by HAugustijn** [comment]
The similarity threshold works in the opposite way. If the threshold is set to zero, all gene clusters will form their own gene cluster families, whereas a threshold of one will result in one large family containing all gene clusters. So, instead of using a threshold of 0.9, you should use a threshold of 0.1, which will yield a large number of families (and representatives). I have added some clarification on the threshold in the readme.
